// Auto-generated by update_site_manifest.ps1
// Do not edit manually. Run the script to update.

window.siteManifest = {
    videos: [
    {
        "title":  "Archiv: Structure of Science",
        "category":  "Featured Content",
        "id":  "Archiv__Structure_of_Science",
        "src":  "assets/videos/Archiv__Structure_of_Science.mp4"
    },
    {
        "title":  "AV1 Retina: Hidden Eye",
        "category":  "Featured Content",
        "id":  "AV1_Retina__Hidden_Eye",
        "src":  "assets/videos/AV1_Retina__Hidden_Eye.mp4"
    },
    {
        "title":  "Ethical AI: Inner Character",
        "category":  "Featured Content",
        "id":  "Ethical_AI__Inner_Character",
        "src":  "assets/videos/Ethical_AI__Inner_Character.mp4"
    },
    {
        "title":  "LOOM: Memory is the Mind",
        "category":  "Featured Content",
        "id":  "LOOM__Memory_is_the_Mind",
        "src":  "assets/videos/LOOM__Memory_is_the_Mind.mp4"
    },
    {
        "title":  "The Android Larynx",
        "category":  "Featured Content",
        "id":  "The_Android_Larynx",
        "src":  "assets/videos/The_Android_Larynx.mp4"
    },
    {
        "title":  "The Unified Mind Space",
        "category":  "Featured Content",
        "id":  "The_Unified_Mind_Space",
        "src":  "assets/videos/The_Unified_Mind_Space.mp4"
    }
],
    papers: [
    {
        "year":  "2025",
        "title":  "The Architecture of Mind",
        "link":  "assets/papers/architectureofmind.pdf",
        "desc":  "A unified framework establishing topological equivalence between biological neural networks and symbolic hypergraphs.",
        "tag":  "Intelligence Theory"
    },
    {
        "year":  "2025",
        "title":  "The AV1 Retina",
        "link":  "assets/papers/AV1Retina_Master.pdf",
        "desc":  "Repurposing commodity video codec hardware as ultra-low-power sensory preprocessors for machine vision.",
        "tag":  "Hardware Architecture"
    },
    {
        "year":  "2025",
        "title":  "Biological Architecture for Ethical AI",
        "link":  "assets/papers/biologicalethics.pdf",
        "desc":  "The Hormonal Motivation Framework: implementing biological principles for alignment rather than external constraints.",
        "tag":  "AI Alignment"
    },
    {
        "year":  "2025",
        "title":  "Emergent Deception in AI",
        "link":  "assets/papers/deception-compendium.pdf",
        "desc":  "A compendium arguing that deception is a natural consequence of optimisation in resource-constrained systems.",
        "tag":  "AI Safety"
    },
    {
        "year":  "2025",
        "title":  "The Boundary of Brilliance",
        "link":  "assets/papers/edgeofchaos.pdf",
        "desc":  "A tale of order, chaos, and universal minds. Exploring criticality as the optimal regime for intelligence.",
        "tag":  "Complexity Science"
    },
    {
        "year":  "2025",
        "title":  "Epistemic Homeostasis",
        "link":  "assets/papers/EpistemicHomeostasis.pdf",
        "desc":  "A Systems-Level Framework for AI Governance via Asymmetric Ising Dynamics.",
        "tag":  "AI Governance"
    },
    {
        "year":  "2025",
        "title":  "Epistemic Homeostasis: Orchestrator",
        "link":  "assets/papers/EpistemicHomeostasis_Orchestrator.pdf",
        "desc":  "Technical implementation guide and experimental validation for the belief governance framework.",
        "tag":  "Technical Report"
    },
    {
        "year":  "2025",
        "title":  "The Emergent Vortex-Information Model",
        "link":  "assets/papers/evim_complete.pdf",
        "desc":  "A unified mathematical framework modeling intelligence as persistent, scale-free patterns of information flow.",
        "tag":  "Intelligence Theory"
    },
    {
        "year":  "2025",
        "title":  "Growth-Based AGI",
        "link":  "assets/papers/growth-based-agi-whitepaper.pdf",
        "desc":  "Pathways to Artificial General Intelligence through iterative growth dynamics and architectural evolution.",
        "tag":  "AGI Research"
    },
    {
        "year":  "2025",
        "title":  "The Unified Mind Space (UMS) Framework",
        "link":  "assets/papers/The Unified Mind Space (UMS) Framework.pdf",
        "desc":  "A rigorous topological framework for mapping state-spaces of diverse cognitive systems.",
        "tag":  "Cognitive Science"
    }
]
};
